using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using UnityEngine;
using UnityEditor;

namespace UnityProBuilder
{
    /// <summary>
    /// 
    /// </summary>
    public static class UnityProBuilder
    {
        private static readonly string sAndroidBuildConfig = Path.Combine(Application.dataPath, "AndoridBuild.txt");
        private static readonly string siOSBuildConfig = Path.Combine(Application.dataPath, "iOSBuild.txt");
        private static readonly string sWindowsBuildConfig = Path.Combine(Application.dataPath, "Windows.txt");

        private static readonly string sDebugBatchPath = Path.Combine(Application.dataPath, "../BuildDebug");
        private static readonly string sReleaseBatchPath = Path.Combine(Application.dataPath, "../BuildRelease");

        private static string GetDebugBatchPath(BuildTarget platform, string ext)
        {
            return string.Concat(sDebugBatchPath, "-", platform.ToString(), ext);
        }

        private static string GetReleaseBatchPath(BuildTarget platform, string ext)
        {
            return string.Concat(sReleaseBatchPath, "-", platform.ToString(), ext);
        }

        [MenuItem("BuildTools/ExportAndroid")]
        public static void ExportAndroid()
        {
            DefaultUnityBuildPipeline.Launch(sAndroidBuildConfig);
        }

        [MenuItem("BuildTools/ExportGradleProject")]
        public static void ExportAndroidGradleProject()
        {
            DefaultUnityBuildPipeline.Launch(sAndroidBuildConfig);
        }

        [MenuItem("BuildTools/ExportiOS")]
        public static void ExportiOS()
        {
            DefaultUnityBuildPipeline.Launch(siOSBuildConfig);
        }

        [MenuItem("BuildTools/ExportWindows")]
        public static void ExportWindows()
        {
            DefaultUnityBuildPipeline.Launch(sWindowsBuildConfig);
        }

        [MenuItem("BuildTools/Generate Shells")]
        public static void GenerateShells()
        {
            GenerateWindowsBatch(GetDebugBatchPath(BuildTarget.Android, ".bat"), "UnityProBuilder.UnityProBuilder.ExportAndroid", "build_android.log", "-android -quit");
            GenerateMacShell(GetDebugBatchPath(BuildTarget.Android, ".sh"), "UnityProBuilder.UnityProBuilder.ExportAndroid", "build_android.log", "-android -quit");
            GenerateMacShell(GetDebugBatchPath(BuildTarget.iOS, ".sh"), "UnityProBuilder.UnityProBuilder.ExportiOS", "build_iOS.log", "-ios -quit");
        }

        private static void GenerateWindowsBatch(string path, string method, string logFileName, string otherParams = null)
        {
#if UNITY_EDITOR_WIN
            string pathOfUnity = Process.GetCurrentProcess().MainModule.FileName;

            StringBuilder sb = new StringBuilder(1024);
            sb.AppendLine("REM ##################################################################")
                .AppendLine("REM This file is generated by UnityProBuilder, Please do not modify it.")
                .AppendLine("REM ##################################################################")
                .AppendLine("REM Set Unity Path.")
                .Append("set UNITY_PATH=\"").Append(pathOfUnity).AppendLine("\"")
                .AppendLine("set PROJECT_PATH=%~dp0")
                .Append("%UNITY_PATH% -batchmode -projectPath %PROJECT_PATH% -executeMethod ")
                .Append(method)
                .Append(" -logFile %PROJECT_PATH%")
                .Append(logFileName)
                .Append(" ")
                .AppendLine(otherParams);

            File.WriteAllText(path, sb.ToString());
#endif
        }

        private static void GenerateMacShell(string path, string method, string logFileName, string otherParams = null)
        {
#if UNITY_EDITOR_OSX
            string pathOfUnity = Process.GetCurrentProcess().MainModule.FileName;
            if (!pathOfUnity.StartsWith("/", StringComparison.CurrentCulture))
            {
                pathOfUnity = Path.Combine("/Applications/Unity/Unity.app/Contents/MacOS", pathOfUnity);
            }

            StringBuilder sb = new StringBuilder(1024);
            sb.AppendLine("###################################################################")
                .AppendLine("#!/bin/bash")
                .AppendLine("PROJECT_PATH=''")
                .Append("UNITY_PATH='").Append(pathOfUnity).AppendLine("'")
                .Append("$UNITY_PATH -batchmode -projectPath $PROJECT_PATH -executeMethod ")
                .Append(method)
                .Append(" -logFile $PROJECT_PATH ")
                .Append(logFileName)
                .Append(" ")
                .AppendLine(otherParams);

            File.WriteAllText(path, sb.ToString());
            var chmodProcess = new Process();
            var chmodStartInfo = new ProcessStartInfo();
            chmodStartInfo.WindowStyle = ProcessWindowStyle.Normal;
            chmodStartInfo.FileName = "/bin/chmod";
            chmodStartInfo.Arguments = string.Concat("+x \"", path, "\"");
            chmodProcess.StartInfo = chmodStartInfo;
            chmodProcess.Start();
            chmodProcess.WaitForExit();
#endif
        }

        [MenuItem("BuildTools/Generate All Configs")]
        public static void GenerateConfigs()
        {
            DefaultUnityBuildConfig empty = new DefaultUnityBuildConfig();
            empty.FillWithProject(BuildTarget.Android);
            File.WriteAllText(sAndroidBuildConfig, JsonUtility.ToJson(empty));

            empty.FillWithProject(BuildTarget.iOS);
            File.WriteAllText(siOSBuildConfig, JsonUtility.ToJson(empty));

            GenerateShells();
            AssetDatabase.Refresh();
        }
    }
}
