REM ##################################################################
REM This file is generated by UnityProBuilder, Please do not modify it.
REM ##################################################################
REM Set Unity Path.
set UNITY_PATH="F:\Program Files\Unity\Unity2018.2.11\Editor\Unity.exe"
set PROJECT_PATH=%~dp0
%UNITY_PATH% -batchmode -projectPath %PROJECT_PATH% -executeMethod UnityProBuilder.UnityProBuilder.ExportAndroid -logFile %PROJECT_PATH%build_android.log -android -quit
